package server

import (
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"time"

	"github.com/wllamasr/minecraft-server-mgr/daemon/internal/store"
)

const versionManifestURL = "https://launchermeta.mojang.com/mc/game/version_manifest_v2.json"

type versionManifest struct {
	Versions []struct {
		ID  string `json:"id"`
		URL string `json:"url"`
	} `json:"versions"`
}

type versionMeta struct {
	Downloads struct {
		Server struct {
			URL string `json:"url"`
		} `json:"server"`
	} `json:"downloads"`
}

// provision runs the background pipeline for a freshly created server.
func (m *Manager) provision(s store.Server) {
	emit := func(line, level string) { m.hub.PushLog(s.ID, line, level) }
	emit(fmt.Sprintf("Provisioning server %q...", s.Name), "INFO")

	jar := filepath.Join(s.Dir, "server.jar")
	emit("Downloading Minecraft "+s.MinecraftVersion+" server jar...", "INFO")
	if err := downloadVanillaServer(s.MinecraftVersion, jar); err != nil {
		m.failProvision(s.ID, err)
		return
	}

	emit("Writing server.properties and accepting the EULA...", "INFO")
	if err := os.WriteFile(filepath.Join(s.Dir, "server.properties"), []byte(defaultProperties(s)), 0o640); err != nil {
		m.failProvision(s.ID, err)
		return
	}
	if err := os.WriteFile(filepath.Join(s.Dir, "eula.txt"), []byte("eula=true\n"), 0o640); err != nil {
		m.failProvision(s.ID, err)
		return
	}

	emit("Ensuring a compatible Java runtime is installed...", "INFO")
	if _, err := m.java.Ensure(s.MinecraftVersion, func(line string) { emit(line, "INFO") }); err != nil {
		m.failProvision(s.ID, err)
		return
	}

	m.clearProvisioning(s.ID)
	emit("✔ Provisioning complete — the server is ready to start.", "INFO")
	m.broadcast(s.ID, StatusStopped)
}

func (m *Manager) failProvision(id string, err error) {
	m.setProvisioning(id, StatusError)
	m.hub.PushLog(id, "✖ Provisioning failed: "+err.Error(), "ERROR")
	m.broadcast(id, StatusError)
}

func downloadVanillaServer(mcVersion, dest string) error {
	var manifest versionManifest
	if err := getJSON(versionManifestURL, &manifest); err != nil {
		return err
	}
	var metaURL string
	for _, v := range manifest.Versions {
		if v.ID == mcVersion {
			metaURL = v.URL
			break
		}
	}
	if metaURL == "" {
		return fmt.Errorf("Minecraft version %s not found in manifest", mcVersion)
	}

	var meta versionMeta
	if err := getJSON(metaURL, &meta); err != nil {
		return err
	}
	if meta.Downloads.Server.URL == "" {
		return fmt.Errorf("no server download available for Minecraft %s", mcVersion)
	}
	return downloadFile(meta.Downloads.Server.URL, dest)
}

func getJSON(url string, target any) error {
	client := &http.Client{Timeout: 30 * time.Second}
	resp, err := client.Get(url)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return fmt.Errorf("GET %s: HTTP %d", url, resp.StatusCode)
	}
	return json.NewDecoder(resp.Body).Decode(target)
}

func downloadFile(url, dest string) error {
	if err := os.MkdirAll(filepath.Dir(dest), 0o750); err != nil {
		return err
	}
	client := &http.Client{Timeout: 10 * time.Minute}
	resp, err := client.Get(url)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return fmt.Errorf("download %s: HTTP %d", url, resp.StatusCode)
	}
	tmp := dest + ".part"
	out, err := os.Create(tmp)
	if err != nil {
		return err
	}
	if _, err := io.Copy(out, resp.Body); err != nil {
		out.Close()
		return err
	}
	if err := out.Close(); err != nil {
		return err
	}
	return os.Rename(tmp, dest)
}

func defaultProperties(s store.Server) string {
	lines := []string{
		"#Minecraft server properties",
		"#Generated by msmd (Minecraft Server Manager daemon)",
		fmt.Sprintf("server-port=%d", s.Port),
		"motd=A Minecraft Server managed by MSM",
		"max-players=20",
		"level-name=world",
		"gamemode=survival",
		"difficulty=easy",
		"online-mode=true",
		"white-list=false",
		"pvp=true",
		"enable-command-block=false",
		"spawn-protection=16",
		"view-distance=10",
		"simulation-distance=10",
		"",
	}
	return strings.Join(lines, "\n")
}

var unsafeName = regexp.MustCompile(`[^a-zA-Z0-9_-]`)

func sanitizeName(name string) string {
	return unsafeName.ReplaceAllString(name, "_")
}

func newID() string {
	b := make([]byte, 16)
	_, _ = rand.Read(b)
	return hex.EncodeToString(b)
}
