package server

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"time"

	"github.com/wllamasr/minecraft-server-mgr/daemon/internal/httpx"
	"github.com/wllamasr/minecraft-server-mgr/daemon/internal/loader"
	"github.com/wllamasr/minecraft-server-mgr/daemon/internal/modpack"
	"github.com/wllamasr/minecraft-server-mgr/daemon/internal/store"
)

const versionManifestURL = "https://launchermeta.mojang.com/mc/game/version_manifest_v2.json"

type versionManifest struct {
	Versions []struct {
		ID  string `json:"id"`
		URL string `json:"url"`
	} `json:"versions"`
}

type versionMeta struct {
	Downloads struct {
		Server struct {
			URL string `json:"url"`
		} `json:"server"`
	} `json:"downloads"`
}

// provision runs the background pipeline for a freshly created server.
func (m *Manager) provision(s store.Server) {
	emit := func(line, level string) { m.hub.PushLog(s.ID, line, level) }
	emit(fmt.Sprintf("Provisioning server %q...", s.Name), "INFO")

	jar := filepath.Join(s.Dir, "server.jar")
	emit("Downloading Minecraft "+s.MinecraftVersion+" server jar...", "INFO")
	if err := downloadVanillaServer(s.MinecraftVersion, jar); err != nil {
		m.failProvision(s.ID, err)
		return
	}

	emit("Writing server.properties and accepting the EULA...", "INFO")
	if err := os.WriteFile(filepath.Join(s.Dir, "server.properties"), []byte(defaultProperties(s)), 0o640); err != nil {
		m.failProvision(s.ID, err)
		return
	}
	if err := os.WriteFile(filepath.Join(s.Dir, "eula.txt"), []byte("eula=true\n"), 0o640); err != nil {
		m.failProvision(s.ID, err)
		return
	}

	emit("Ensuring a compatible Java runtime is installed...", "INFO")
	javaPath, err := m.java.Ensure(s.MinecraftVersion, func(line string) { emit(line, "INFO") })
	if err != nil {
		m.failProvision(s.ID, err)
		return
	}

	if s.ModpackURL != "" {
		emit("Applying modpack "+s.ModpackName+"...", "INFO")
		res, err := modpack.Apply(s.Dir, s.ModpackURL, javaPath, func(line string) { emit(line, "INFO") })
		if err != nil {
			m.failProvision(s.ID, err)
			return
		}
		// The pack pins the exact MC version and loader; persist them.
		if res.MinecraftVersion != "" {
			s.MinecraftVersion = res.MinecraftVersion
		}
		s.ModLoader = res.Loader
		s.ModLoaderVersion = res.LoaderVersion
		s.UpdatedAt = time.Now().UTC().Format(time.RFC3339)
		if err := m.store.Put(s); err != nil {
			m.failProvision(s.ID, err)
			return
		}
	} else if s.ModLoader != "" {
		emit(fmt.Sprintf("Installing %s %s...", s.ModLoader, s.ModLoaderVersion), "INFO")
		if err := loader.Install(loader.Type(s.ModLoader), s.ModLoaderVersion, s.MinecraftVersion, s.Dir, javaPath,
			func(line string) { emit(line, "INFO") }); err != nil {
			m.failProvision(s.ID, err)
			return
		}
	}

	m.clearProvisioning(s.ID)
	emit("✔ Provisioning complete — the server is ready to start.", "INFO")
	m.broadcast(s.ID, StatusStopped)
}

func (m *Manager) failProvision(id string, err error) {
	m.setProvisioning(id, StatusError)
	m.hub.PushLog(id, "✖ Provisioning failed: "+err.Error(), "ERROR")
	m.broadcast(id, StatusError)
}

func downloadVanillaServer(mcVersion, dest string) error {
	var manifest versionManifest
	if err := httpx.GetJSON(versionManifestURL, &manifest); err != nil {
		return err
	}
	var metaURL string
	for _, v := range manifest.Versions {
		if v.ID == mcVersion {
			metaURL = v.URL
			break
		}
	}
	if metaURL == "" {
		return fmt.Errorf("Minecraft version %s not found in manifest", mcVersion)
	}

	var meta versionMeta
	if err := httpx.GetJSON(metaURL, &meta); err != nil {
		return err
	}
	if meta.Downloads.Server.URL == "" {
		return fmt.Errorf("no server download available for Minecraft %s", mcVersion)
	}
	return httpx.Download(meta.Downloads.Server.URL, dest)
}

func defaultProperties(s store.Server) string {
	lines := []string{
		"#Minecraft server properties",
		"#Generated by msmd (Minecraft Server Manager daemon)",
		fmt.Sprintf("server-port=%d", s.Port),
		"motd=A Minecraft Server managed by MSM",
		"max-players=20",
		"level-name=world",
		"gamemode=survival",
		"difficulty=easy",
		"online-mode=true",
		"white-list=false",
		"pvp=true",
		"enable-command-block=false",
		"spawn-protection=16",
		"view-distance=10",
		"simulation-distance=10",
		"",
	}
	return strings.Join(lines, "\n")
}

var unsafeName = regexp.MustCompile(`[^a-zA-Z0-9_-]`)

func sanitizeName(name string) string {
	return unsafeName.ReplaceAllString(name, "_")
}

func newID() string {
	b := make([]byte, 16)
	_, _ = rand.Read(b)
	return hex.EncodeToString(b)
}
