/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServersIndexRouteImport } from './routes/servers/index'
import { Route as ModsIndexRouteImport } from './routes/mods/index'
import { Route as ServersCreateRouteImport } from './routes/servers/create'
import { Route as ServersServerIdRouteImport } from './routes/servers/$serverId'
import { Route as ConsoleServerIdRouteImport } from './routes/console/$serverId'
import { Route as ConfigServerIdRouteImport } from './routes/config/$serverId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServersIndexRoute = ServersIndexRouteImport.update({
  id: '/servers/',
  path: '/servers/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModsIndexRoute = ModsIndexRouteImport.update({
  id: '/mods/',
  path: '/mods/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServersCreateRoute = ServersCreateRouteImport.update({
  id: '/servers/create',
  path: '/servers/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ServersServerIdRoute = ServersServerIdRouteImport.update({
  id: '/servers/$serverId',
  path: '/servers/$serverId',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleServerIdRoute = ConsoleServerIdRouteImport.update({
  id: '/console/$serverId',
  path: '/console/$serverId',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigServerIdRoute = ConfigServerIdRouteImport.update({
  id: '/config/$serverId',
  path: '/config/$serverId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/config/$serverId': typeof ConfigServerIdRoute
  '/console/$serverId': typeof ConsoleServerIdRoute
  '/servers/$serverId': typeof ServersServerIdRoute
  '/servers/create': typeof ServersCreateRoute
  '/mods/': typeof ModsIndexRoute
  '/servers/': typeof ServersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/config/$serverId': typeof ConfigServerIdRoute
  '/console/$serverId': typeof ConsoleServerIdRoute
  '/servers/$serverId': typeof ServersServerIdRoute
  '/servers/create': typeof ServersCreateRoute
  '/mods': typeof ModsIndexRoute
  '/servers': typeof ServersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/config/$serverId': typeof ConfigServerIdRoute
  '/console/$serverId': typeof ConsoleServerIdRoute
  '/servers/$serverId': typeof ServersServerIdRoute
  '/servers/create': typeof ServersCreateRoute
  '/mods/': typeof ModsIndexRoute
  '/servers/': typeof ServersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/config/$serverId'
    | '/console/$serverId'
    | '/servers/$serverId'
    | '/servers/create'
    | '/mods/'
    | '/servers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/config/$serverId'
    | '/console/$serverId'
    | '/servers/$serverId'
    | '/servers/create'
    | '/mods'
    | '/servers'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/config/$serverId'
    | '/console/$serverId'
    | '/servers/$serverId'
    | '/servers/create'
    | '/mods/'
    | '/servers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  ConfigServerIdRoute: typeof ConfigServerIdRoute
  ConsoleServerIdRoute: typeof ConsoleServerIdRoute
  ServersServerIdRoute: typeof ServersServerIdRoute
  ServersCreateRoute: typeof ServersCreateRoute
  ModsIndexRoute: typeof ModsIndexRoute
  ServersIndexRoute: typeof ServersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servers/': {
      id: '/servers/'
      path: '/servers'
      fullPath: '/servers/'
      preLoaderRoute: typeof ServersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mods/': {
      id: '/mods/'
      path: '/mods'
      fullPath: '/mods/'
      preLoaderRoute: typeof ModsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servers/create': {
      id: '/servers/create'
      path: '/servers/create'
      fullPath: '/servers/create'
      preLoaderRoute: typeof ServersCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servers/$serverId': {
      id: '/servers/$serverId'
      path: '/servers/$serverId'
      fullPath: '/servers/$serverId'
      preLoaderRoute: typeof ServersServerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/$serverId': {
      id: '/console/$serverId'
      path: '/console/$serverId'
      fullPath: '/console/$serverId'
      preLoaderRoute: typeof ConsoleServerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config/$serverId': {
      id: '/config/$serverId'
      path: '/config/$serverId'
      fullPath: '/config/$serverId'
      preLoaderRoute: typeof ConfigServerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  ConfigServerIdRoute: ConfigServerIdRoute,
  ConsoleServerIdRoute: ConsoleServerIdRoute,
  ServersServerIdRoute: ServersServerIdRoute,
  ServersCreateRoute: ServersCreateRoute,
  ModsIndexRoute: ModsIndexRoute,
  ServersIndexRoute: ServersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
